[package]
name = "blockfloat"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
thiserror.workspace = true

[dev-dependencies]
divan = "0.1"
serde_json.workspace = true

[[bench]]
name = "fp8_linear"
harness = false

[lints]
workspace = true
