use super::*;

use serde_json::Value;

// Generated by scripts/flow-match-reference.py from the FLUX.2-klein-4B and
// Qwen-Image-2.1 scheduler configs; see the fixture's "versions".
const FIXTURE: &str = include_str!("../../../../fixtures/flow-match/sigmas.json");

fn bits(values: &Value) -> Vec<u32> {
    values
        .as_array()
        .expect("bit list")
        .iter()
        .map(|hex| u32::from_str_radix(hex.as_str().expect("hex"), 16).expect("hex bits"))
        .collect()
}

fn to_bits(values: impl IntoIterator<Item = f32>) -> Vec<u32> {
    values.into_iter().map(f32::to_bits).collect()
}

fn mu(rule: &str, config: &FlowMatchConfig, seq_len: usize, steps: usize) -> Option<f64> {
    if !config.uses_dynamic_shifting() {
        return None;
    }
    Some(match rule {
        "flux2_empirical" => flux2_empirical_mu(seq_len, steps),
        "linear" => linear_mu(config, seq_len),
        other => panic!("unknown mu rule {other}"),
    })
}

#[test]
fn sigmas_and_timesteps_match_diffusers_bit_for_bit() {
    let fixture: Value = serde_json::from_str(FIXTURE).expect("fixture JSON");
    let mut compared = 0;
    let mut refused = 0;
    for schedule in fixture["schedules"].as_array().expect("schedules") {
        let name = schedule["name"].as_str().expect("name");
        let rule = schedule["mu_rule"].as_str().expect("rule");
        let config = FlowMatchConfig::from_json(&schedule["config"].to_string()).expect("config");
        for case in schedule["cases"].as_array().expect("cases") {
            let steps = usize::try_from(case["steps"].as_u64().expect("steps")).unwrap();
            let seq_len = usize::try_from(case["image_seq_len"].as_u64().expect("len")).unwrap();
            let mu = mu(rule, &config, seq_len, steps);
            // Bit patterns, not JSON numbers: serde_json's default float parse
            // is not correctly rounded and was off by one ulp here.
            if let (Some(ours), Some(source)) = (mu, case["mu_f64_bits"].as_str()) {
                let source = f64::from_bits(u64::from_str_radix(source, 16).expect("hex"));
                assert_eq!(
                    ours.to_bits(),
                    source.to_bits(),
                    "{name} mu, {steps} steps, {seq_len}"
                );
            }
            let source_bits = bits(&case["sigmas_f32_bits"]);
            if source_bits.iter().any(|&b| f32::from_bits(b).is_nan()) {
                // diffusers yields NaN sigmas here; refusing is the contract.
                assert_eq!(
                    Sigmas::new(&config, steps, mu),
                    Err(ScheduleError::DegenerateTerminal),
                    "{name}, {steps} steps, {seq_len} tokens"
                );
                refused += 1;
                continue;
            }
            let sigmas = Sigmas::new(&config, steps, mu).expect("schedule");
            assert_eq!(
                to_bits(sigmas.as_slice().iter().copied()),
                bits(&case["sigmas_f32_bits"]),
                "{name} sigmas, {steps} steps, {seq_len} tokens"
            );
            assert_eq!(
                to_bits(sigmas.steps().map(|step| step.timestep)),
                bits(&case["timesteps_f32_bits"]),
                "{name} timesteps, {steps} steps, {seq_len} tokens"
            );
            compared += 1;
        }
    }
    // Qwen-Image-2.1 at one step is the only degenerate case.
    assert_eq!(refused, 6);
    assert_eq!(
        compared + refused,
        2 * 8 * 6,
        "only {compared} cases compared"
    );
}

// Control: the bit comparison must notice a wrong but plausible schedule.
// FLUX.2's mu depends on the step count below 4300 tokens; a mu fitted for a
// neighbouring step count has to change the sigmas.
#[test]
fn a_neighbouring_step_count_mu_changes_the_sigmas() {
    let fixture: Value = serde_json::from_str(FIXTURE).expect("fixture JSON");
    let klein = &fixture["schedules"][0];
    assert_eq!(klein["mu_rule"], "flux2_empirical");
    let config = FlowMatchConfig::from_json(&klein["config"].to_string()).expect("config");
    let case = klein["cases"]
        .as_array()
        .unwrap()
        .iter()
        .find(|case| case["steps"] == 4 && case["image_seq_len"] == 4096)
        .expect("4-step 1024x1024 case");
    let wrong = Sigmas::new(&config, 4, Some(flux2_empirical_mu(4096, 5))).unwrap();
    assert_ne!(
        to_bits(wrong.as_slice().iter().copied()),
        bits(&case["sigmas_f32_bits"])
    );
}

const KLEIN: &str = r#"{
  "_class_name": "FlowMatchEulerDiscreteScheduler",
  "base_image_seq_len": 256, "base_shift": 0.5, "invert_sigmas": false,
  "max_image_seq_len": 4096, "max_shift": 1.15, "num_train_timesteps": 1000,
  "shift": 3.0, "shift_terminal": null, "stochastic_sampling": false,
  "time_shift_type": "exponential", "use_beta_sigmas": false,
  "use_dynamic_shifting": true, "use_exponential_sigmas": false,
  "use_karras_sigmas": false
}"#;

#[test]
fn sampler_changing_options_are_refused() {
    let stochastic = KLEIN.replace(
        "\"stochastic_sampling\": false",
        "\"stochastic_sampling\": true",
    );
    assert_eq!(
        FlowMatchConfig::from_json(&stochastic),
        Err(ScheduleError::Unsupported("stochastic_sampling"))
    );
    let other = KLEIN.replace("FlowMatchEulerDiscreteScheduler", "DDIMScheduler");
    assert!(matches!(
        FlowMatchConfig::from_json(&other),
        Err(ScheduleError::Class(_))
    ));
}

#[test]
fn mu_is_required_exactly_with_dynamic_shifting() {
    let config = FlowMatchConfig::from_json(KLEIN).unwrap();
    assert_eq!(Sigmas::new(&config, 4, None), Err(ScheduleError::MissingMu));
    assert_eq!(
        Sigmas::new(&config, 0, Some(1.0)),
        Err(ScheduleError::NoSteps)
    );
    let fixed = FlowMatchConfig::from_json(&KLEIN.replace(
        "\"use_dynamic_shifting\": true",
        "\"use_dynamic_shifting\": false",
    ))
    .unwrap();
    assert_eq!(
        Sigmas::new(&fixed, 4, Some(1.0)),
        Err(ScheduleError::UnexpectedMu)
    );
}

#[test]
fn steps_walk_the_sigmas_to_zero() {
    let config = FlowMatchConfig::from_json(KLEIN).unwrap();
    let sigmas = Sigmas::new(&config, 4, Some(flux2_empirical_mu(4096, 4))).unwrap();
    let steps: Vec<_> = sigmas.steps().collect();
    assert_eq!(steps.len(), 4);
    assert_eq!(steps[0].sigma, 1.0);
    assert_eq!(steps[3].sigma_next, 0.0);
    assert!(steps.iter().all(|step| step.dt() < 0.0));
}

#[test]
fn nonfinite_mu_is_refused() {
    let config = FlowMatchConfig::from_json(KLEIN).unwrap();
    for mu in [f64::NAN, f64::INFINITY, f64::NEG_INFINITY] {
        assert!(Sigmas::new(&config, 4, Some(mu)).is_err(), "mu={mu}");
    }
}

#[test]
fn unrepresentable_dynamic_scales_are_refused() {
    let exponential = FlowMatchConfig::from_json(KLEIN).unwrap();
    for mu in [1000.0, 100.0, -1000.0] {
        assert!(Sigmas::new(&exponential, 4, Some(mu)).is_err(), "mu={mu}");
    }
    let linear = FlowMatchConfig::from_json(&KLEIN.replace("exponential", "linear")).unwrap();
    for mu in [0.0, -1.0, 1e100, 1e-100, f64::from(f32::from_bits(1))] {
        assert!(Sigmas::new(&linear, 4, Some(mu)).is_err(), "mu={mu}");
    }
}

#[test]
fn invalid_static_shift_and_training_count_are_refused() {
    for shift in ["0.0", "-1.0", "1e100", "1e-100"] {
        assert!(
            FlowMatchConfig::from_json(
                &KLEIN.replace("\"shift\": 3.0", &format!("\"shift\": {shift}"))
            )
            .is_err(),
            "shift={shift}"
        );
    }
    assert!(
        FlowMatchConfig::from_json(&KLEIN.replace(
            "\"num_train_timesteps\": 1000",
            "\"num_train_timesteps\": 0"
        ))
        .is_err()
    );
}

#[test]
fn terminal_rounding_cannot_silently_disable_or_destroy_the_schedule() {
    for terminal in ["1e-100", "0.9999999999999999"] {
        assert!(
            FlowMatchConfig::from_json(&KLEIN.replace(
                "\"shift_terminal\": null",
                &format!("\"shift_terminal\": {terminal}")
            ))
            .is_err(),
            "terminal={terminal}"
        );
    }
    let tiny = FlowMatchConfig::from_json(
        &KLEIN.replace("\"shift_terminal\": null", "\"shift_terminal\": 1e-40"),
    )
    .unwrap();
    assert!(Sigmas::new(&tiny, 4, Some(1.0)).is_err());
}

#[test]
fn static_float32_cancellation_is_refused() {
    let config = FlowMatchConfig::from_json(
        &KLEIN
            .replace(
                "\"use_dynamic_shifting\": true",
                "\"use_dynamic_shifting\": false",
            )
            .replace("\"shift\": 3.0", "\"shift\": 1e-20"),
    )
    .unwrap();
    assert!(Sigmas::new(&config, 4, None).is_err());
}

#[test]
fn valid_scale_edges_stay_finite_and_timesteps_stay_bounded() {
    let near_one = FlowMatchConfig::from_json(
        &KLEIN
            .replace("\"shift_terminal\": null", "\"shift_terminal\": 0.99999994")
            .replace(
                "\"num_train_timesteps\": 1000",
                "\"num_train_timesteps\": 4294967295",
            ),
    )
    .unwrap();
    let schedule = Sigmas::new(&near_one, 4, Some(1.0)).unwrap();
    for step in schedule.steps() {
        assert!(step.sigma.is_finite() && step.sigma > 0.0 && step.sigma <= 1.0);
        assert!(step.sigma_next <= step.sigma);
        assert!(
            step.timestep.is_finite() && step.timestep > 0.0 && step.timestep <= 4_294_967_296.0
        );
    }
    let exponential = FlowMatchConfig::from_json(KLEIN).unwrap();
    assert!(Sigmas::new(&exponential, 4, Some(0.0)).is_ok());
    let linear = FlowMatchConfig::from_json(&KLEIN.replace("exponential", "linear")).unwrap();
    assert!(Sigmas::new(&linear, 4, Some(1.0)).is_ok());
}
